<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEMrM2Wi\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEMrM2Wi/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEMrM2Wi.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEMrM2Wi\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerEMrM2Wi\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'EMrM2Wi',
    'container.build_id' => '53c09a78',
    'container.build_time' => 1523770487,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEMrM2Wi');
